id: P004543
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6430
  title: བོད་ཀྱི་པད་ཚལ་རིགས་ཀྱི་དགུན་དུས་པད་ཁ་འདེབས་འཇུགས་ལག་རྩལ།
  author: ''
  volumes:
    dd1fe7c715c6408ca1aa39880e87547f:
      image_group_id: I3CN6432
      title: ''
      volume_number: 1
      total_pages: 78
      base_file: v001.txt
